# Generated by Django 4.2.23 on 2025-08-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='userid',
        ),
    ]
