# Generated by Django 4.2.23 on 2025-08-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_remove_attendance_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='qr',
            field=models.ImageField(blank=True, upload_to='qr/'),
        ),
    ]
