# Generated by Django 4.2.23 on 2025-08-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_register_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='userid',
        ),
    ]
